services:
  flask-app:
    container_name: flask-app
    image: ingsw2324_52/backend
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    command: python -u main.py
    ports:  
      - "4000:4000"
    environment:  
      DB_URL_DOCKER: postgresql://postgres:Blacks27@flask_db:5432/postgres
    depends_on:
      - flask_db
    
  flask_db:
    container_name: flask_db
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: "Blacks27"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Backend/Backend_SQL/Dump:/docker-entrypoint-initdb.d

#frontend:
#    container_name: react-app
#    build: 
#      context: ./Frontend
#      dockerfile: Dockerfile
#    ports:
#      - "3000:80"
#    depends_on:
#      - flask-app

volumes:
  postgres_data: