services:
  flask-app:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=/app/app.py
      - FLASK_ENV=development
      - DB_URL_DOCKER=postgresql://postgres:Blacks27@flask_db:5432/postgres
    depends_on:
      - flask_db
    volumes:
      - ./Backend/Backend_Python:/app
    command: ["flask", "--app", "/app/app.py", "run", "--host=0.0.0.0", "--port=5000"]

  flask_db:
    container_name: flask_db
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: "Blacks27"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Backend/Backend_SQL/Dump:/docker-entrypoint-initdb.d

volumes:
  postgres_data:

#frontend:
#    container_name: react-app
#    build: 
#      context: ./Frontend
#      dockerfile: Dockerfile
#    ports:
#      - "3000:80"
#    depends_on:
#      - flask-app