services:
  flask-app:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=Backend_Python.main:app
      - FLASK_ENV=development
      - DB_URL_DOCKER=postgresql://postgres_ingsw52_user:ZxyNuWqn3cmXwVBXbbr1id82MkTCRA4s@dpg-ctdvlk2lqhvc73daigl0-a.frankfurt-postgres.render.com/postgres_ingsw52
    depends_on:
      - flask_db
    volumes:
      - ./Backend:/app

  flask_db:
    container_name: flask_db
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: "Blacks27"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Backend/Backend_SQL/Dump:/docker-entrypoint-initdb.d

  frontend:
    container_name: react-app
    build: 
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./Frontend/dist:/usr/share/nginx/html
    depends_on:
      - flask-app

volumes:
  flask_app_data:
  postgres_data: